### ISSUE TITLE
JSON API link is not working

### ISSUE THREAD

**Issue by limsocheat** [dwilkie/pumi#23]

**Comment by dwilkie** [comment]
Fixed thanks!

**Comment by limsocheat** [comment]
Hi @dwilkie, I think the API link is stop working: https://pumiapp.herokuapp.com/

**Comment by dwilkie** [comment]
@limsocheat I just deployed it to https://pumi.onrender.com/

**Comment by limsocheat** [comment]
> @limsocheat I just deployed it to https://pumi.onrender.com/

Noted with thanks.
